# Generated by Django 3.1.2 on 2021-06-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ad_category_goods_goodsimage_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
